let
  # Use a recent nixpkgs so Cargo understands the v4 Cargo.lock generated by
  # current Rust toolchains.
  pkgs = import (fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  }) {};
in
pkgs.mkShell {
  packages = with pkgs; [
    rustc
    cargo
    rustfmt
    clippy
    pkg-config
    openssl
    cacert
    gcc
  ];

  # Available for crates that use OpenSSL directly; reqwest currently uses rustls.
  PKG_CONFIG_PATH = "${pkgs.openssl.dev}/lib/pkgconfig";
  OPENSSL_DIR = pkgs.openssl.dev;
  SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
}
