//! `agentd gen-systemd`: sessions that should outlive the user session are
//! supervised by systemd, not by agentd — the supervisor knows how to
//! *generate* the unit, the init system owns restart-on-failure
//! (docs/SUPERVISOR.md "Design stance").
//!
//! `Type=forking` + `PIDFile` fits the CLI's process model exactly:
//! `agentd resume` spawns the detached agent, writes `<name>/pid`, and
//! exits; systemd tracks the agent via the pid file and re-runs
//! `agentd resume` (latest checkpoint) on failure.

use std::path::Path;

pub fn unit_name(name: &str) -> String {
    format!("agentd-{name}.service")
}

pub fn unit(name: &str, home: &Path, agentd_bin: &Path) -> String {
    let dir = home.join(name);
    format!(
        "# GENERATED by `agentd gen-systemd {name}` — edits are overwritten by agentd.\n\
         # The canonical session config is {spec}\n\
         # (edit it directly or via `agentd set-model`/`set-*`), not this unit.\n\
         \n\
         [Unit]\n\
         Description=agentd session {name}\n\
         \n\
         [Service]\n\
         Type=forking\n\
         PIDFile={pid}\n\
         Environment=AGENTD_HOME={home}\n\
         ExecStart={bin} resume {name}\n\
         ExecStop={bin} stop {name}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        name = name,
        spec = dir.join(crate::spec::SPEC_FILE).display(),
        pid = dir.join("pid").display(),
        home = home.display(),
        bin = agentd_bin.display(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn unit_has_the_generated_header_and_restart_policy() {
        let text = unit(
            "coder",
            &PathBuf::from("/home/ben/.local/share/agentd"),
            &PathBuf::from("/usr/bin/agentd"),
        );
        assert!(text.starts_with("# GENERATED by `agentd gen-systemd coder`"));
        assert!(text.contains("edits are overwritten by agentd"));
        assert!(text.contains("Type=forking\n"));
        assert!(text.contains("PIDFile=/home/ben/.local/share/agentd/coder/pid\n"));
        assert!(text.contains("ExecStart=/usr/bin/agentd resume coder\n"));
        assert!(text.contains("ExecStop=/usr/bin/agentd stop coder\n"));
        assert!(text.contains("Restart=on-failure\n"));
        assert!(text.contains("WantedBy=default.target\n"));
        assert_eq!(unit_name("coder"), "agentd-coder.service");
    }
}
